services:
  whatsapp:
    image: ghcr.io/aldinokemal/go-whatsapp-web-multidevice
    container_name: whatsapp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=false
      - --os=Chrome
      - --account-validation=false
      - --webhook=http://fastapi-klique:8000/webhooks/whatsapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:latest
    container_name: mongodb_kliqueq
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: klique  # Nome do banco padrão
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  fastapi-app:
    container_name: fastapi-klique
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SECRET_KEY: a8b28eaaa2aa5cd246d7318435738f5c914feb474051c72b7d54429ff51194fc
      GOOGLE_API_KEY: AIzaSyBgtTWw5XS1X6JdE-sddspxqCeM4nWl7iw
      GOOGLE_APPLICATION_CREDENTIALS: "creds.json"
      GOOGLE_DRIVE_ROOT_FOLDER_ID: "1e6T4wsPmPjuP-8qzWUkD2RAmZeGXT8IR"
      DB_CONNECTION: mongodb
      DB_HOST: mongodb_kliqueq
      DB_PORT: 27017
      DB_DATABASE: klique
      DB_USERNAME: root
      DB_PASSWORD: password
      GMAIL_EMAIL: ${GMAIL_EMAIL}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD} # Senha de app do Gmail
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      PUTER_API_KEY: ${PUTER_API_KEY}
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - gemini_cookies:/usr/local/lib/python3.12/site-packages/gemini_webapi/utils/temp
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  g4f:
    image: hlohaus789/g4f:latest
    container_name: g4f
    ports:
      - "8080:8080"
      - "7900:7900"
    shm_size: "2g"
    volumes:
      - ./har_and_cookies:/app/har_and_cookies
      - ./generated_media:/app/generated_media
    restart: always

volumes:
  mongodb_data:
  whatsapp:
  gemini_cookies:
  har_and_cookies:
  generated_media: