[project]
name = "klique-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "browser-cookie3>=0.20.1",
    "fastapi[standard]>=0.116.1",
    "gemini-webapi>=1.15.0",
    "motor>=3.7.1",
    "passlib[bcrypt]>=1.7.4",
    "pillow>=11.3.0",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "rich>=14.1.0",
]
